const disabilityList = [
    {
        dscThai: "ตาบอดสนิท",
        dscEng: "Without Vision",
        shortness: "WV",
        flag: 1,
        expTh: "นักฟังยอดเยี่ยม",
        expEng: "The Excellent Listener Team",

    },
    {
        dscThai: "มองเห็นเลือนลาง",
        dscEng: "Limited Vision",
        shortness: "LV",
        flag: 2,
        expTh: "นักสืบแว่นขยาย",
        expEng: "The Magnifier Team",
    },
    {
        dscThai: "ตาบอดสี",
        dscEng: "Without Perception of Colour",
        shortness: "WPC",
        flag: 4,
        expTh: "นักเห็นต่าง",
        expEng: "The Different Viewer",
    },
    {
        dscThai: "หูหนวกสนิท",
        dscEng: "Without Hearing",
        shortness: "WH",
        flag: 8,
        expTh: "นักช่างสังเกตุ",
        expEng: "The Great Observer Team",
    },
    {
        dscThai: "หูตึง",
        dscEng: "Limited Hearing",
        shortness: "LH",
        flag: 16,
        expTh: "นักสืบแอบฟัง",
        expEng: "The Wire Tap Team",
    },
    {
        dscThai: "ไม่สามารถสื่อสารด้วยเสียง",
        dscEng: "Without Vocal Capability",
        shortness: "WVC",
        flag: 32,
        expTh: "นักมือปืนไว",
        expEng: "The Quick Hands Team",
    },
    {
        dscThai: "แขนขาอ่อนแรง",
        dscEng: "Limited manipulation or strength",
        shortness: "LMS",
        flag: 64,
        expTh: "ผู้สั่งการหลังแผงควบคุม",
        expEng: "The Commander Team",
    },
    {
        dscThai: "การเคลื่อนไหวจำกัด",
        dscEng: "Limited mobility",
        shortness: "LM",
        flag: 128,
        expTh: "นักบินขาเหล็ก",
        expEng: "The Metal-Leg Pilot team",
    },
    {
        dscThai: "ไวต่อแสง",
        dscEng: "Photo Seizure Triggers",
        shortness: "PST",
        flag: 256,
        expTh: "นักสายตาเฉียบชม",
        expEng: "The Laser Eye Team",
    },
    {
        dscThai: "การคิดวิเคราะห์จำกัด",
        dscEng: "Limited Cognition",
        shortness: "LC",
        flag: 512,
        expTh: "นักขี้เล่น",
        expEng: "The Playful Team",
    },
    {
        dscThai: "การเรียนรู้จำกัด",
        dscEng: "Limited Learning Capability",
        shortness: "LL",
        flag: 1024,
        expTh: "นักช่างสงสัย",
        expEng: "The Curiousity Team",
    },
    {
        dscThai: "สูงอายุ",
        dscEng: "Elderly",
        shortness: "E",
        flag: 2048,
        expTh: "นักปราชญ์",
        expEng: "The Wisdom Team",
    },
    {
        dscThai: "อาการซึมเศร้า",
        dscEng: "Depression",
        shortness: "D",
        flag: 4096,
        expTh: "ผู้พิทักษ์ที่ห่วงใย",
        expEng: "The Caring Guardian Team",
    },
    {
        dscThai: "ออทิสติกสเปกตรัม",
        dscEng: "Autism Spectrum",
        shortness: "AS",
        flag: 8192,
        expTh: "นักช่างใส่ใจ",
        expEng: "The Attentive Team",
    },

];

export default disabilityList;